extends Node
## Central audio playback. Four buses (Master, Music, Ambience, SFX).
## All shipped sounds are original synthesized WAV loops generated by
## tools/generate_audio.py (no third-party audio).

var _music_player: AudioStreamPlayer
var _ambience_player: AudioStreamPlayer
var _sfx_pool: Array[AudioStreamPlayer] = []
var _streams: Dictionary = {}
var _current_music: String = ""


func _ready() -> void:
	_music_player = AudioStreamPlayer.new()
	_music_player.bus = "Music"
	add_child(_music_player)
	_ambience_player = AudioStreamPlayer.new()
	_ambience_player.bus = "Ambience"
	add_child(_ambience_player)
	for i in 8:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_sfx_pool.append(p)
	_load_streams()


func _load_streams() -> void:
	var dir := DirAccess.open("res://assets/audio")
	if dir == null:
		return
	for fname in dir.get_files():
		var clean := fname.trim_suffix(".import")
		if not clean.ends_with(".wav"):
			continue
		var res: Resource = load("res://assets/audio/" + clean)
		if res is AudioStream:
			_streams[clean.get_basename()] = res


func has_sound(sound_name: String) -> bool:
	return _streams.has(sound_name)


func play_sfx(sound_name: String, pitch_variance: float = 0.05) -> void:
	if not _streams.has(sound_name):
		return
	for p in _sfx_pool:
		if not p.playing:
			p.stream = _streams[sound_name]
			p.pitch_scale = 1.0 + randf_range(-pitch_variance, pitch_variance)
			p.play()
			return


## Plays a positional sound through a caller-provided AudioStreamPlayer3D.
func attach_stream(player: AudioStreamPlayer3D, sound_name: String, loop_it: bool = false) -> void:
	if not _streams.has(sound_name):
		return
	var s: AudioStream = _streams[sound_name]
	if loop_it and s is AudioStreamWAV:
		var dup: AudioStreamWAV = (s as AudioStreamWAV).duplicate()
		dup.loop_mode = AudioStreamWAV.LOOP_FORWARD
		dup.loop_end = dup.data.size() / 2  # 16-bit mono frames
		player.stream = dup
	else:
		player.stream = s
	player.bus = "Ambience" if loop_it else "SFX"


func play_music(track: String) -> void:
	if _current_music == track or not _streams.has(track):
		return
	_current_music = track
	var s: AudioStream = _streams[track]
	if s is AudioStreamWAV:
		var dup: AudioStreamWAV = (s as AudioStreamWAV).duplicate()
		dup.loop_mode = AudioStreamWAV.LOOP_FORWARD
		dup.loop_end = dup.data.size() / 2
		_music_player.stream = dup
	else:
		_music_player.stream = s
	_music_player.play()


func play_ambience(track: String) -> void:
	if not _streams.has(track):
		_ambience_player.stop()
		return
	var s: AudioStream = _streams[track]
	if s is AudioStreamWAV:
		var dup: AudioStreamWAV = (s as AudioStreamWAV).duplicate()
		dup.loop_mode = AudioStreamWAV.LOOP_FORWARD
		dup.loop_end = dup.data.size() / 2
		_ambience_player.stream = dup
	_ambience_player.play()


func stop_music() -> void:
	_current_music = ""
	_music_player.stop()


func apply_volumes(master: float, music: float, ambience: float, sfx: float) -> void:
	_set_bus("Master", master)
	_set_bus("Music", music)
	_set_bus("Ambience", ambience)
	_set_bus("SFX", sfx)


func _set_bus(bus_name: String, linear: float) -> void:
	var idx := AudioServer.get_bus_index(bus_name)
	if idx >= 0:
		AudioServer.set_bus_volume_db(idx, linear_to_db(clampf(linear, 0.0001, 1.0)))
