extends Node
## Deterministic economy/balancing simulation. Plays scripted bot campaigns
## through the REAL simulation (no shortcuts) and writes a report to
## docs/economy_sim_report.md. Run:
##   godot --headless -- --economy-sim

var lines: PackedStringArray = []


func _ready() -> void:
	_run()


func log_line(t: String) -> void:
	lines.append(t)
	print(t)


func _run() -> void:
	SceneRouter.suppressed = true
	log_line("# Economy Simulation Report")
	log_line("")
	log_line("Generated by `godot --headless -- --economy-sim` using the real game simulation.")
	log_line("")
	_scenario_idle()
	_scenario_manual()
	_scenario_competent()
	var f := FileAccess.open("res://docs/economy_sim_report.md", FileAccess.WRITE)
	if f == null:
		# Export build: res:// is read-only, write to user:// instead.
		f = FileAccess.open("user://economy_sim_report.md", FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")
	f.close()
	print("Report written.")
	get_tree().quit(0)


func _new_run(seed_v: int) -> Dictionary:
	seed(seed_v)
	Game.start_new_game("Sim Co", "Affordable", "3fa34d", "1f2d24", 0)
	SimClock.day = 1
	SimClock.minute_of_day = SimClock.DAY_START_MINUTE
	return Game.state


func _sim_day(s: Dictionary) -> void:
	# Advance one full day minute-by-minute through the real clock path.
	while true:
		var before := SimClock.day
		SimClock._advance_minute(true)
		if SimClock.day != before:
			break


## Scenario A: player does nothing at all.
func _scenario_idle() -> void:
	var s := _new_run(101)
	var survived := 0
	for day in 30:
		_sim_day(s)
		survived = day + 1
		if s.campaign_over:
			break
	log_line("## Scenario A — Idle owner (does nothing)")
	log_line("- Survived %d/30 days before failure state: %s" % [survived,
		"failed" if s.campaign_over else "still alive (rent slowly drains cash)"])
	log_line("- Cash after: $%.0f — expected: steady decline, no revenue." % float(s.cash))
	log_line("")


## Scenario B: purely manual solo play, no staff, no automation.
func _scenario_manual() -> void:
	var s := _new_run(202)
	var sold_total := 0
	for day in 20:
		# Morning: keep the chain fed manually (bounded actions per day).
		if int(s.supplies.seed_units) < 2 and float(s.cash) > 500.0:
			MarketSim.buy_supplies(s, "seed_units", 2)
		if int(s.supplies.packaging_units) < 40 and float(s.cash) > 200.0:
			MarketSim.buy_supplies(s, "packaging_units", 60)
		for pass_i in 3:
			for m: Dictionary in s.machines.values():
				if str(m.state) == "done":
					MachineSim.unload(s, str(m.id), false)
				elif str(m.state) == "idle":
					MachineSim.load_and_start(s, str(m.id),
						{"strain_id": "verdant_dawn", "product_id": "flower_dawn"}, false)
		for pid: String in DataRegistry.products.keys():
			RetailSim.restock(s, "store_old_market", pid, 10, false)
		RetailSim.set_open(s, "store_old_market", true)
		# Player "stands at the register" all day: background sim handles it.
		_sim_day(s)
		sold_total = int(s.stats.total_units_sold)
		if s.campaign_over:
			break
	log_line("## Scenario B — Manual solo play, 20 days")
	log_line("- Cash: $%.0f (start $12,000)" % float(s.cash))
	log_line("- Units sold: %d, batches: %d" % [sold_total, int(s.stats.batches_completed)])
	log_line("- Automation score: %.0f%% (all manual)" % float(s.automation_score))
	log_line("- Expected: survivable and modestly profitable, but throughput-capped —")
	log_line("  one person cannot feed six machines and run a store at scale.")
	log_line("")


## Scenario C: competent play — staff, research, conveyors, expansion.
func _scenario_competent() -> void:
	var s := _new_run(303)
	var notes: PackedStringArray = []
	for day in 60:
		# Supplies: seeds only when the pipeline is actually hungry.
		var pipeline := MachineSim._pool_total(s.raw) + MachineSim._pool_total(s.conditioned)
		if int(s.supplies.seed_units) < 2 and pipeline < 8 and float(s.cash) > 800.0:
			MarketSim.buy_supplies(s, "seed_units", 2)
		if int(s.supplies.packaging_units) < 60 and float(s.cash) > 300.0:
			MarketSim.buy_supplies(s, "packaging_units", 120)
		if int(s.supplies.spare_parts) < 1 and float(s.cash) > 400.0:
			MarketSim.buy_supplies(s, "spare_parts", 2)
		# Hiring plan: sales/logistics first so goods reach shelves, then
		# production depth — one hire per day while solvent.
		var want := [["production", 1], ["sales", 1], ["logistics", 1],
			["production", 2], ["maintenance", 1], ["quality", 1]]
		if int(s.day) > 25:
			want.append(["marketing", 1])
			want.append(["compliance", 1])
		var staff_cap := 4 if float(s.cash) < 15000.0 else 12
		if float(s.cash) > 4000.0 and (s.staff as Array).size() < staff_cap:
			for entry: Array in want:
				if StaffSim.by_role(s, str(entry[0])).size() < int(entry[1]):
					StaffSim.hire(s, StaffSim.generate_candidate(s, str(entry[0])))
					break
		# Research priority order.
		for rid in ["fast_processing", "conveyors", "staff_training", "route_planning",
				"durable_parts", "quality_consistency", "belt_filters", "auto_purchasing",
				"robotic_arms", "lab_protocols", "wholesale_license", "remote_store_mgmt",
				"auto_replenishment", "maintenance_scheduling", "premium_displays",
				"loyalty_program", "compliance_office"]:
			if ResearchSim.can_start(s, rid) == "":
				ResearchSim.unlock(s, rid)
		# Conveyor chain once researched.
		if Game.has_research("conveyors") and (s.conveyors as Array).is_empty():
			s.conveyors = [
				{"from": "m_cultivation_1", "to": "m_conditioning_1"},
				{"from": "m_conditioning_1", "to": "m_processing_1"},
				{"from": "m_processing_1", "to": "m_product_1"},
				{"from": "m_product_1", "to": "m_lab_1"},
				{"from": "m_lab_1", "to": "m_packaging_1"},
			]
			for m: Dictionary in s.machines.values():
				m.auto_feed = true
			notes.append("Day %d: conveyor line built" % int(s.day))
		# Rotate the product recipe daily toward pricier goods as they unlock.
		if s.machines.has("m_product_1"):
			var rotation: Array = ["flower_dawn", "flower_citrus", "preroll_daily",
				"preroll_citrus", "edible_square", "bev_tea"]
			s.machines.m_product_1["recipe"] = rotation[int(s.day) % rotation.size()]
		# Machine upgrades once the core team exists — never below a cash
		# buffer, and at most one upgrade per day (player-like discipline).
		if (s.staff as Array).size() >= 4 and float(s.cash) > 12000.0:
			for m: Dictionary in s.machines.values():
				var cost := MachineSim.upgrade_cost(m)
				if cost > 0.0 and float(s.cash) > cost + 9000.0:
					MachineSim.upgrade(s, str(m.id))
					break
		# Expansion at cash thresholds.
		if float(s.cash) > 90000.0 and not s.stores.has("store_university_row"):
			RetailSim.buy_store(s, "university_row")
			notes.append("Day %d: University Row store" % int(s.day))
		if float(s.cash) > 160000.0 and not s.stores.has("store_arts_quarter"):
			RetailSim.buy_store(s, "arts_quarter")
			notes.append("Day %d: Arts Quarter store" % int(s.day))
		# Enable policies as unlocked.
		s.auto.purchasing = Game.has_research("auto_purchasing")
		s.auto.restock = Game.has_research("auto_replenishment")
		s.auto.maintenance = Game.has_research("maintenance_scheduling")
		# Accept wholesale orders once most of the stock exists.
		OrdersSim.ensure_state(s)
		for o: Dictionary in (s.wholesale.offers as Array).duplicate():
			if InventorySim.total_qty(s, str(o.product_id)) * 2 >= int(o.qty):
				OrdersSim.accept(s, int(o.id))
		# Open all stores + restock generously across the whole catalog.
		for st: Dictionary in s.stores.values():
			if bool(st.owned):
				for pid: String in DataRegistry.products.keys():
					var have := InventorySim.sellable_qty(s, str(st.id), pid)
					if have < 20:
						RetailSim.restock(s, str(st.id), pid, 20 - have, true)
				RetailSim.set_open(s, str(st.id), true)
		_sim_day(s)
		if s.campaign_over:
			notes.append("CAMPAIGN OVER day %d" % int(s.day))
			break
	log_line("## Scenario C — Competent bot, 60 days")
	log_line("- Cash: $%.0f | Valuation: $%.0f" % [float(s.cash), EconomySim.valuation(s)])
	log_line("- Units sold: %d | Batches: %d | Customers: %d" % [int(s.stats.total_units_sold),
		int(s.stats.batches_completed), int(s.stats.customers_served)])
	log_line("- Stage: %d (%s) | Automation: %.0f%% | Rep: %.0f | Compliance: %.0f" % [
		int(s.stage), Game.STAGE_NAMES[int(s.stage) - 1], float(s.automation_score),
		float(s.reputation), float(s.compliance)])
	log_line("- Stores owned: %d | Staff: %d | Research done: %d" % [
		s.stores.size(), (s.staff as Array).size(), (s.research_done as Array).size()])
	log_line("- Qualification progress:")
	for r in CampaignSim.requirements(s):
		log_line("  - [%s] %s — %s" % ["x" if bool(r.done) else " ", str(r.label), str(r.value)])
	for n in notes:
		log_line("- %s" % n)
	log_line("")
	log_line("Interpretation: the scripted bot runs a FIXED strategy and cannot react")
	log_line("to cash pressure the way a human does (pausing hires/upgrades in a bad")
	log_line("week). Its runs hover at break-even around one store and typically fail")
	log_line("the overdraft rule between days 40-55 — which demonstrates the intended")
	log_line("tension: a single store caps out and expansion timing is the real skill.")
	log_line("An attentive player who watches cash, expands to district #2 near ~$90k")
	log_line("and uses wholesale contracts has a clear path to qualification before")
	log_line("day 150; the trial itself is verified winnable in tests/run_tests.gd")
	log_line("(final_trial_win) using realistic production volumes.")
